/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Database.DBConnection;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ChitietTL extends javax.swing.JFrame {

    /**
     * Creates new form ChitietTL
     * @param user
     * @param nd
     * @param baocao
     * @param ch
     * @param tl
     */
    public ChitietTL(String user,String nd,String baocao,String ch,String tl) {
        try {
            initComponents();
            connection=new DBConnection();
            con=connection.DBConnection();
            setDefaultCloseOperation(ChitietTL.HIDE_ON_CLOSE);
            ChitietTL.user=user;
            ChitietTL.nd=nd;
            ChitietTL.baocao=baocao;
            ChitietTL.ch=ch;
            ChitietTL.tl=tl;
            txtNoidung.setLineWrap(true);
            txtNoidung.setWrapStyleWord(true);
            hienthi();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ChitietTL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    DBConnection connection;
    Connection con;
    Statement stm;
    static String user,nd,baocao,ch,tl;
    private void hienthi(){
        txtNoidung.setText(user+"\n"
                            +nd.replace("\\n%", "\n"));
        lbBaocao.setText("Báo cáo"+baocao);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoidung = new javax.swing.JTextArea();
        btnBaocao = new javax.swing.JButton();
        lbBaocao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi tiết câu trả lời");
        setResizable(false);

        txtNoidung.setColumns(20);
        txtNoidung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNoidung.setRows(5);
        txtNoidung.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNoidung.setEnabled(false);
        jScrollPane1.setViewportView(txtNoidung);

        btnBaocao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBaocao.setText("Báo cáo");
        btnBaocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaocaoActionPerformed(evt);
            }
        });

        lbBaocao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbBaocao.setText("jLabel1");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBaocao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBaocao, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaocao)
                    .addComponent(lbBaocao)
                    .addComponent(jButton1))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ChitietCH chitietCH=new ChitietCH(ch,user);
        this.setVisible(false);
        chitietCH.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBaocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaocaoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            stm=con.createStatement();
            String sql="update AnswerInfor set Report=Report+1 where AnswerID='"+tl+"'";
            stm.executeUpdate(sql);
            //JOptionPane.showMessageDialog(rootPane, tl);
            hienthi();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnBaocaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChitietTL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChitietTL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChitietTL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChitietTL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChitietTL(user,nd,baocao,ch,tl).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaocao;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBaocao;
    private javax.swing.JTextArea txtNoidung;
    // End of variables declaration//GEN-END:variables
}
