/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Database.DBConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ChitietCH extends javax.swing.JFrame {

    DBConnection connection;
    Connection con;
    ResultSet rs;
    Statement stm;
    /**
     * Creates new form ChitietCH
     * @param maCH
     * @param email
     */
    static String maCH,email;
    public ChitietCH(String maCH, String email) {
        initComponents();
        connection=new DBConnection();
        try {
            con=connection.DBConnection();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ChitietCH.class.getName()).log(Level.SEVERE, null, ex);
        }
        setDefaultCloseOperation(ChitietCH.HIDE_ON_CLOSE);
        ChitietCH.maCH=maCH;
        ChitietCH.email=email;
        hienthiCH();
        txtNoidung.setLineWrap(true);
        txtNoidung.setWrapStyleWord(true);
        hienthiTL();
    }

    private void hienthiCH(){
        try {
            String sql="select * from QuestInfor where QuestID='"+maCH+"'";
            stm=con.createStatement();
            rs=stm.executeQuery(sql);
            while(rs.next()){
                String tieude=rs.getString("QuestTitle").replace("\\n%", "\n");
                String tag=rs.getString("QuestTag");
                String baocao="Báo cáo: "+rs.getString("Report");
                String user=rs.getString("Username");
                String noidung=rs.getString("QuestContent").replace("\\n%", "\n");
                txtNoidung.setText("Câu hỏi: "+tieude+"\n\nNhãn: "
                        + tag+"\nNgười đăng: "
                        + user+"\n\n"
                        + noidung);
                lbBaocao.setText(baocao);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChitietCH.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void hienthiTL(){
        try{
            String sql="select * from AnswerInfor where QuestID='"+maCH+"'";
            rs=stm.executeQuery(sql);
            int i=1;
            DefaultTableModel dtm=new DefaultTableModel();
            dtm.addColumn("STT");
            dtm.addColumn("Mã trả lời");
            dtm.addColumn("Người đăng");
            dtm.addColumn("Mã câu hỏi");
            dtm.addColumn("Nội dung");
            dtm.addColumn("Báo cáo");
            dtm.setRowCount(0);
            while(rs.next()){
                dtm.addRow(new Object[]{
                    i,
                    rs.getString("AnswerID"),
                    rs.getString("Username"),
                    rs.getString("QuestID"),
                    rs.getString("Answer"),
                    rs.getString("Report")
                });
                i++;
            }
            tbview.setModel(dtm);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoidung = new javax.swing.JTextArea();
        lbBaocao = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbview = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi tiết câu hỏi");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết câu hỏi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jScrollPane1.setEnabled(false);

        txtNoidung.setColumns(20);
        txtNoidung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNoidung.setRows(5);
        txtNoidung.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNoidung.setEnabled(false);
        jScrollPane1.setViewportView(txtNoidung);

        lbBaocao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbBaocao.setText("Báo cáo");

        tbview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbviewMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbview);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Báo cáo câu hỏi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Trả lời");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Tải lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBaocao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBaocao)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String sql="update QuestInfor set Report=Report+1 where QuestID='"+maCH+"'";
            stm.executeUpdate(sql);
            hienthiCH();
        } catch (SQLException ex) {
            Logger.getLogger(ChitietCH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbviewMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)tbview.getModel();
        int dongchon=tbview.getSelectedRow();
        String tl=dtm.getValueAt(dongchon, 1).toString();
        String user=dtm.getValueAt(dongchon, 2).toString();
        String ch=dtm.getValueAt(dongchon, 3).toString();
        String nd=dtm.getValueAt(dongchon, 4).toString();
        String baocao=dtm.getValueAt(dongchon, 5).toString();
        ChitietTL chitietTL=new ChitietTL(user, nd,baocao,ch,tl);
        this.setVisible(false);
        chitietTL.setVisible(true);
    }//GEN-LAST:event_tbviewMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hienthiTL();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TraLoi tl=new TraLoi(email, maCH);
        this.setVisible(false);
        tl.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChitietCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChitietCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChitietCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChitietCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChitietCH(maCH,email).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbBaocao;
    private javax.swing.JTable tbview;
    private javax.swing.JTextArea txtNoidung;
    // End of variables declaration//GEN-END:variables
}
